project_id = "fenwpejwqpeiiukageur"

[functions.hr-chat]
verify_jwt = false

[functions.analyze-resume]
verify_jwt = false

[functions.send-analysis-notification]
verify_jwt = false

[functions.match-job-description]
verify_jwt = false

[functions.send-interview-reminders]
verify_jwt = false
